# External gems
plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag

# Site settings
title: Last Rose Studios Dev Blog
subtitle: "Development Blog for Last Rose Studios"
email: devblog@lastrose.com
name: Last Rose Studios
description: > 
  Coding tricks picked up while working on sites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://devblog.lastrose.com/" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"
permalink: /:title/
# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
future: false
# Disqus comments
disqus_shortname: lastrosestudiosinc

# Google analytics
ga_tracking_id: "G-HP9M043Z6R"

# Category descriptions (for archive pages)
descriptions:
  - cat: Platforms
    desc: "Posts about different platforms we work with."

  - cat: Programming
    desc: "Posts about some solutions we came up with"
   
# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: https://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: Twitter
    icon: twitter
    username: "@lastrosestudios"
    url: https://twitter.com/lastrosestudios
    desc: Follow me on Twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - name: Facebook
    icon: facebook
    username: 
    url: 
    desc: Friend me on Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - name: GitHub
    icon: github
    username: lastrose
    url: https://github.com/lastrose
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin
    username: Last Rose Studios
    url: https://www.linkedin.com/company/last-rose-studios-inc-
    desc: Connect with me on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: ?mini=true
    share_link: "&amp;url="

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share_url: 
    share_title: 
    share_link:

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share_url: 
    share_title: 
    share_link:

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share_url: 
    share_title: 
    share_link:

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share_url: 
    share_title: 
    share_link:

  - name: Tumblr
    icon: tumblr
    username: 
    url: 
    desc: Follow me on Tumblr
    share_url: 
    share_title: 
    share_link:

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share_url: 
    share_title: 
    share_link:

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
